version: '3.8' # Adicione a versão para garantir compatibilidade

services:
  app:
    build: .
    container_name: marketplace_app
    restart: always
    ports:
      - "3001:3000" 
    env_file:
      - .env.local
